# Generated by Django 5.2 on 2025-05-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partit',
            name='gols_local',
        ),
    ]
